<!-- BEGIN:agents-kbs-tech-stack -->
# Agent Fleet — {PROJECT_NAME}

> Generated by agents-kbs-tech-stack on {LAST_UPDATED}.
> Re-run `emit-cross-tool.sh` after adding or removing a tech.

When writing code for this project, apply the knowledge and conventions from the relevant domain below. Each domain has a paired architect (design decisions) and developer (implementation) agent grounded in a curated KB.

## Available Agents

{AGENTS_TABLE}

## Knowledge Base Domains

{KB_TABLE}

## How to apply

- **Architecture decisions** — follow patterns from `*-architect` agent KB (concepts/ + patterns/).
- **Implementation** — follow conventions from `*-developer` agent KB (patterns/ + reference/).
- **Debugging** — use `*-troubleshooter` agent KB.
- **Code review / simplify / document** — use the closer agents (`code-reviewer`, `code-simplifier`, `code-documenter`), which are grounded in every domain KB.
- Quick-reference docs per domain are linked in the KB table above — read them before suggesting code in that domain.
<!-- END:agents-kbs-tech-stack -->
